name: Deploy project plan to heroku

on:
  push:
    branches: [ master ]

jobs:
  build-frontend:
    name: build project plan react frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: run npm install and build
        run: |
          cd cgn-web-20-2-project-plan/frontend
          npm install
          npm run build
      - name: upload frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: cgn-web-20-2-project-plan/frontend/build/

  build-backend:
    name: build jar file
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: download frontend build artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: cgn-web-20-2-project-plan/project-planning/src/main/resources/static
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file ./cgn-web-20-2-project-plan/project-planning/pom.xml
      - name: upload project-planning.jar file
        uses: actions/upload-artifact@v2
        with:
          name: project-planning.jar
          path: cgn-web-20-2-project-plan/project-planning/target/project-planning.jar

  deploy:
    name: deploy to heroku
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - name: create target folder
        run: mkdir cgn-web-20-2-project-plan/project-planning/target
      - name: download project-planning.jar
        uses: actions/download-artifact@v2
        with:
          name: project-planning.jar
          path: cgn-web-20-2-project-plan/project-planning/target
      - name: login to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: heroku build/push container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web -a super-idea-planning
      - name: release container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a super-idea-planning